### ISSUE TITLE
Can I record multiple live broadcasts at the same time？

### ISSUE THREAD

**Issue by Nek0Neko** [Stefomat/twitch-stream-recorder#16]

**Comment by Stefomat** [comment]
I'm sorry I didn't respond. You can record several streams at the same time if you run several containers at the same time. A container only records one stream at a time. As an example, here is an excerpt for a docker-compose.yml that records streamer_A and streamer_B. You only have to change the service name, the container name and the username.
```
---
version: "2"

services:
  twitch-stream-recorder_A:
    image: ghcr.io/stefomat/twitch-stream-recorder:master
    container_name: twitch-stream-recorder_A
    environment:
      - USERNAME=streamer_A
      - CLIENT_ID=your_client_id
      - CLIENT_SECRET=your_client_secret
      - AUTH_TOKEN=your_oauth_token_cookie
    volumes:
      - /path/to/recordings:/opt/recordings
    restart: unless-stopped

  twitch-stream-recorder_B:
    image: ghcr.io/stefomat/twitch-stream-recorder:master
    container_name: twitch-stream-recorder_B
    environment:
      - USERNAME=streamer_B
      - CLIENT_ID=your_client_id
      - CLIENT_SECRET=your_client_secret
      - AUTH_TOKEN=your_oauth_token_cookie
    volumes:
      - /path/to/recordings:/opt/recordings
    restart: unless-stopped
```
